cpu/microarchitectures.json
VSX alitvec extensions are supported by PowerISA from v2.06 (Power7+), but might
not be listed in features.
FMA has been supported by PowerISA since Power1, but might not be listed in
features.
This commit adds these features to all the power ISA family sets.
=> Adds fma and vsx features to entire power arch family.

.github/workflows/validation.yml, README.md, cpu/microarchitectures.json, cpu/microarchitectures_schema.json
fixes #1
When complete this PR will:
=> Simplify types in microarchitecture's JSON file

cpu/microarchitectures.json
Instead of suffixing the version of Clang with "-apple" change the name of Apple compiler to "apple-clang"
=> Don't use version suffix to distinguish among compilers

LICENSE-MIT, README.md
Archspec grew out of Spack, so we initially just labeled it that way, but it's really its own project. I put in a separate code release for Archspec, so now we don't have to mention Spack in all the code headers.
=> Archspec now has its own release number

cpu/microarchitectures.json
This PR adds the AWS Graviton2 processors to archspec.
=> Add AWS Graviton2

cpu/microarchitectures.json
The support has been inserted combining:
1. The support for LLVM Clang already present
2. The version translation table present at https://en.wikipedia.org/wiki/Xcode
=> Added support for apple-clang (Intel uarchs)

cpu/microarchitectures.json
Architecture flags have been added for the AOCC compiler in file microarchitectures.json given below
File:
archspec-json/cpu/microarchitectures.json
=> Added architecture flags for AOCC compiler

cpu/microarchitectures.json
Discovered by a Spack user using intel@19.0.0. The 19.0.0 compiler does not support cascadelake, the 19.0.1 compiler does.
See https://software.intel.com/content/www/us/en/develop/articles/intel-c-compiler-190-for-linux-release-notes-for-intel-parallel-studio-xe-2019.html#history
=> Fix version range for cascadelake/intel

cpu/microarchitectures.json
Removed 'erms' from microarchitectures.json for znver3
=> Removed 'erms' from microarchitectures.json for znver3

cpu/microarchitectures.json
Removed entries invpcid,ospke, pku, in  znver3 section as they are not required for detection of znver3
=> Removed entries invpcid,ospke, pku, in  znver3 section

cpu/microarchitectures.json
I just compiled the development version of GCC and:
```
znver3
AMD Family 19h core based CPUs with x86-64 instruction set support. (This supersets BMI, BMI2, CLWB, F16C, FMA, FSGSBASE, AVX, AVX2, ADCX, RDSEED, MWAITX, SHA, CLZERO, AES, PCLMUL,
CX16, MOVBE, MMX, SSE, SSE2, SSE3, SSE4A, SSSE3, SSE4.1, SSE4.2, ABM, XSAVEC, XSAVES, CLFLUSHOPT, POPCNT, RDPID, WBNOINVD, PKU, VPCLMULQDQ, VAES, and 64-bit instruction set
extensions.)
```
It seems that zen3 has PKU, VPCLMULQDQ, VAES more with respect to zen2, so adding the missing one and support for GCC
=> zen3: added pku feature, GCC and Clang support

cpu/microarchitectures.json, tests/targets/darwin-bigsur-m1
refers to https://github.com/archspec/archspec/issues/38
This PR adds an entry for Apple M1. Currently I don't have a CPU to test on, so I'm coding this based on reported output from `sysctl`. It seems we don't have much information from Apple, in particular concerning CPU features. I think that all the features listed as `hw.optional` should be added to the JSON file but I still need to double check if this is consistent with the semantics of other `aarch64` architectures. 
Also, the compiler flags are generic for armv8.4-a and not tested on any actual application. It would be good if reviewers could comment on that.
=> Add tentative entry for Apple M1

cpu/microarchitectures.json
This introduces definitions for the [microarchitecture levels](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels):
- `x86-64-v2` (basically an alias to `nehalem` with generic tuning)
- `x86-64-v3` (alias to `haswell` with generic tuning)
- `x86-64-v4` (alias to `skylake_avx512` with generic tuning)
I also implemented equivalent compiler flags for gcc < 11.1 and clang < 12.0.
It's my first PR pm archspec, so I have some doubts about how to tune the compiler version ranges and the features list.
Resolves archspec/archspec-json#30
=> Add support for microarchitecture levels

cpu/microarchitectures.json
When we use arm compiler to compile applications on amazon graviton2 machines, there is a warning that arm compiler cannot build optimized binaries for "graviton2" and turns it to aarch64. Thus, I add this arm section to gravition2. It has passed our testing.
=> add arm compiler support to graviton2

cpu/microarchitectures.json, tests/targets/linux-sifive-u74mc
Add riscv64 arch and u74mc uarch, both of which are needed to support the SiFive Unmatched board.
=> Add riscv64 arch and u74mc uarch

cpu/microarchitectures.json
Vanilla Clang supports tuning for `apple-m1` target since version 13: https://github.com/llvm/llvm-project/commit/a8a3a43792472c9775c60fa79b9357033d47ce40.  Also Apple Clang 13 supports the `apple-m1` target.
I think this may fix #42.  CC: @trws
Side note: I'm not touching GCC, but I'm not sure it makes much sense, especially starting from version 8, since no stable version of GCC can target that platform.  https://github.com/iains/gcc-darwin-arm64 is the only fork of GCC I know which can compile for this platform, at https://github.com/iains/gcc-darwin-arm64/issues/86#issuecomment-1089406128 there is a possible value of `-march` (but at the moment it doesn't do any further optimisation, no support for specific `-mcpu`).
=> Add Clang optimization flags for Apple M1

cpu/microarchitectures.json
* Remove AES feature, apparently not supported in all CPU models.  Also LLVM
doesn't use this feature on this CPU
* `-mpcu=a64fx` is supported in GCC since version 10.3:
<https://www.gnu.org/software/gcc/gcc-10/changes.html>
* `-mcpu=a64fx` is supported in LLVM since version 11:
<https://github.com/llvm/llvm-project/commit/c8cd1a994d28e5e822bd0d3c9a6b0aae2abb510f>
Fix #23.
=> Improve a64fx microarchitecture

cpu/microarchitectures.json
This PR adds the oneapi and dpcpp compilers to archspec. These compilers
are Intel's latest generation compilers and have similar options to the
classic Intel compilers. As such, the entries here are based on the
intel entires.
Note: I also added entries, including for intel, to the zen3 block. If
there was a reason that the intel compiler was not there then the new
entries in that section will need to be removed.
=> Add oneapi compiler

cpu/microarchitectures.json
Version 2021.2.0 introduced support for x86-64-v2, x86-64-v3, and x86-64-v4 arch flags.
=> OneAPI support for x86-64-v[2-4] in 2021.2.0:

cpu/microarchitectures.json
`x86-64` is nowhere in [the intel classic compiler manual section on the `march` flag](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/code-generation-options/march.html). 
```
/modules/spack-0.18.1/lib/spack/env/intel/icc -fPIC -O2 -D_LARGEFILE64_SOURCE=1  -c -o adler32.o adler32.c
icc: command line warning #10148: option '-march=x86-64' not supported
```
This should probably be fact checked on a system that isn't mine.
=> remove x86-64 from intel classic compiler

cpu/microarchitectures.json, tests/targets/linux-rocky8-a64fx
With this change in Spack I finally get on Ookami
```console
$ spack arch
linux-rocky8-a64fx
```
This was missed in #44. Should fix #23. Again.
=> Remove `pmull` feature from A64FX

cpu/microarchitectures.json, tests/targets/linux-ubuntu20.04-zen4
Updated with flags info which will help spack to autodetect zen4
Please note, https://github.com/spack/spack/pull/33833 is the review request for AOCC-4.0.0
=> Update spack to autodetect 4th Generation AMD EPYC processor or zen4

cpu/microarchitectures.json
Intel has dropped support for Xeon Phi processors in their compilers from 2021.3 onward.
https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes-2021.html#inpage-nav-10
https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-dpc-c-compiler-release-notes-2021.html#inpage-nav-6
https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-c-compiler-release-notes.html
=> Intel compilers: Xeon Phi support deprecated

cpu/microarchitectures.json
=> Apple M2: fix microarchitecture optimization flags

cpu/microarchitectures.json
@alalazo @annop-w 
I checked @annop-w spack PR https://github.com/spack/spack/pull/36277 because he wrote he would have to get signoff from his manager to contribute to this repo, so I've checked his changes.
They are mostly correct except that  `-mcpu=neoverse-v1` was already added with `gcc-10.3`:
https://gcc.gnu.org/onlinedocs/gcc-10.3.0/gcc/AArch64-Options.html#AArch64-Options
So the commit message is:
`gcc-10.2` added `-mcpu=zeus` for neoverse-v1 platform
and  `-mcpu=neoverse-v1` was added with `gcc-9.4`, `gcc-10.3` and `gcc-11.0`.
Inspired by https://github.com/spack/spack/pull/36277 by Annop Wongwathanarat 
but updated because for the gcc-10 series, -mcpu=neoverse-v1 started to appear already with gcc-10.3.0:
https://gcc.gnu.org/onlinedocs/gcc-10.3.0/gcc/AArch64-Options.html#AArch64 …
=> neoverse-v1: fix flags for GCC

cpu/microarchitectures.json
Full znver4 support is present as of the 13.1 release.
=> add AMD Zen4 architecture flags for GCC 13.1+

cpu/microarchitectures.json
Complete `znver4` support is present from LLVM 16
=> Add AMD Zen4 Architecture Flags for LLVM 16

cpu/microarchitectures.json
Removing CPU flags to enable compilation inside hypervisors on zen4 processors. These two flags do not represent any compiler options, thus do not influence compatibility of compiled code.
Adding @amd-toolchain-support for review.
=> Remove erms & avic flags from zen4

cpu/microarchitectures.json, tests/targets/linux-ubuntu22.04-neoverse_v2
Add support for Armv9 and Neoverse v2, as required for the Nvidia Grace CPU.
=> Add Neoverse V2 and Armv9

cpu/microarchitectures.json, tests/targets/linux-rhel9-neoverse_v2
These features are not always reported by the operating system.
Fix #83.
=> Remove `paca`, `pacg`, and `bti` from Neoverse V2

cpu/microarchitectures.json, tests/targets/linux-rhel8-neoverse_v1
These features are not always reported by the operating system, and they don't cause SIGILL when not supported by the platform.
=> Remove `paca`, `pacg`, and `bti` from Neoverse V1

cpu/microarchitectures.json
nvhpc added support for zen4 in version 23.9.
=> Update nvhpc zen4 support

cpu/microarchitectures.json
closes #96
Update compilers for v2 architecture.
=> Update compiler versions for neoverse v2

cpu/microarchitectures.json, cpu/microarchitectures_schema.json
As part of https://github.com/archspec/archspec/pull/168 on the archspec repo, it was decided to add, where it made sense for ARM cores a new field, called `cpuid` rather than adding a new submodule just for that.
These changes aim at:
- adding the optional field in the microarchitecture_schema file 
- introducing the field "cpuid" in the ARM microarchitectures 
This field will be used in the cpu/detect.py file in the archspec repo, for which a separate PR will be opened. 
CC: @dslarm
=> Adding optional CPUID field in microarchitecture schema and in json file for Arm architectures

cpu/microarchitectures.json
`PDCM` is not a feature currently used by compilers, see for instance https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html.
For GCP VMs, only ones that have vPMU [enabled](https://cloud.google.com/compute/docs/manage-pmu-in-vms) would have `PDCM` exposed in the guest. Including `PDCM` would therefore cause these non-vPMU-enabled VMs to be identified as icelake instead.
=> Remove `PDCM` from the sapphirerapids list

cpu/microarchitectures.json
Add the generic architectures 
* x86_64_v2
* x86_64_v3
* x86_64_v4
for the AMD AOCC Compiler.
=> Include AOCC in generic architectures

cpu/microarchitectures.json
Motivations for taking `cppc` out:
* There's no upstream support in KVM for this AMD feature, so this won't be trivial to support for KVM-based virtualization. Plus AFAIK this feature isn't used in Linux yet.
* This does not seem to be something a compiler would use. For instance this is not included in GCC's znver5 list: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html.
* There are other existing features that can tell zen5 apart from previous zen generations, for instance `avx_vnni` and `movdiri`, so the removal won't impact correct identification.
=> Remove `cppc` from the zen5 feature list
